### ISSUE TITLE
Can APPIMAGE_UUID be replaced by a random string?

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/AppRun#11]
To simplify things, can `APPIMAGE_UUID` be replaced by a random string in the library internally, so that it does not need to be provided as an environment variable? Or why would one want to provide it manually?

The following appears to work for me:

```
#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"

export APPIMAGE_UUID=$(echo -n $APPDIR | md5sum | awk '{print $1}')
export SYSTEM_INTERP=/lib64/ld-linux-x86-64.so.2
export APPDIR_LIBC_VERSION=2.27
export APPDIR_INTERP=$APPDIR/libc/lib64/ld-linux-x86-64.so.2
export RUNTIME_INTERP=/tmp/ld-$APPIMAGE_UUID.so
export EXEC_PATH=$APPDIR/usr/bin/gedit
export APPDIR_LIBRARY_PATH=$APPDIR/usr/lib64/:$APPDIR/usr/lib64/gtk-3.0/3.0.0/i$
export LD_PRELOAD=$APPDIR/libapprun_hooks.so
exec $EXEC_PATH "$@"
```

As you can see, `APPIMAGE_UUID` and `RUNTIME_INTERP` are automatically populated (in my case, with the md5sum of the string of the path to the AppDir). I wonder why the library would not do something like that internally, and not require these values to be fed in.

**Comment by azubieta** [comment]
APPIMAGE_UUID is a random string, so it's safe what you're doing. Notice that wee need predictable paths for `ld-linux.so`.
This path may be used for other purposes.

Maybe we can consider making a runtime that uses this kind of `UUID` for mounting.

**Comment by probonopd** [comment]
Thanks for the clarification @azubieta.

Would anything prevent the equivalent of

export APPIMAGE_UUID=$(echo -n $APPDIR | md5sum | awk '{print $1}')
export RUNTIME_INTERP=/tmp/ld-$APPIMAGE_UUID.so

to be done internally in `libapprun_hooks.so` so that when `APPIMAGE_UUID` and `RUNTIME_INTERP` are not set, the library would use those as defaults?

**Comment by azubieta** [comment]
Sound like a good idea, I'll add this as fallback.

**Comment by azubieta** [comment]
Just a comment, the startup configuration is done by the `AppRun` binary not by `libapparun_hooks`.

**Comment by probonopd** [comment]
> Just a comment, the startup configuration is done by the AppRun binary not by libapparun_hooks.

please elaborate. I was planning on using `libapparun_hooks.so` from a custom bash `AppRun`, is that not possible, or do I need to take special steps?

**Comment by azubieta** [comment]
The `AppRun` job is to act as a bash replacement, I do started with a bash script too.

Its workflow is:
- read the `.env` file
- expand the variables
- set the environment variables
- *guess* the system glib version. We are guessing here, if the system packager removes the version string from the binary this will fail. This same method is used by flatpack.
- *copy* the right `ld-linux.so` into `RUNTIME_INTERP`. Creating a symlink to a mounted path will case issues if the app is executed several times.
- launch the main binary

**Comment by azubieta** [comment]
The uuid need to be set at build time as it is used to create the interpreter path that is patched inside the binary files. It can be replaced by any random string but bear in mind that it must me unique and also be used in the PT_ITERP path of the bundled files like this: `/tmp/appimage-<uuid>-<interpreter file name>`.

This is valid for AppRun 1.2.0

**Comment by probonopd** [comment]
Is it still mandatory or can it be left away in the `.env` file?

**Comment by azubieta** [comment]
It's mandatory, AppRun will create `/tmp/appimage-<uuid>-ld-linux-x86-64.so.2`. This same path must be set to the elf files, therefore the uuid must be set at build time.

I'm will be conducting an experiment  (#19) next week, if it shows a positive result. We may be able to drop all patchelf usages and this UUID.
