### ISSUE TITLE
bundle multiarch libapprun_hooks and use it in appimages?

### ISSUE THREAD

**Issue by mmtrt** [AppImageCrafters/AppRun#34]
Is it possible to bundle both `i386` and `amd64` since I have `wine` appimage which uses `64b` `32b` in `wineprefixes` if I use suppose only 32b `wineprefix` then it uses `wine` 32b components only to funchtion as per arch but as appimage has only `amd64` libapprun_hooks and it casues logspam.

```
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

```

**Comment by azubieta** [comment]
Yes, that's totally doable. You just need to deploy the binaries in different folders i.e.:
```
$APPDIR/lib/i386/libapprun_hooks.so
$APPDIR/lib/amd64/libapprun_hooks.so
```

Notice that the [latest appimage-builder already does this](https://github.com/AppImageCrafters/appimage-builder/commit/4981a1aad5917b9688ea7439b167c85e8c5b9b59). You will need to install it from master.

**Comment by mmtrt** [comment]
Didn't see these were already in place so using continuous build fixes this issue.

Thank you for your hard work at this.
