### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/AppRun#6]
Hi, interesting project.

To make it really useful, please document this a bit more.
* Can this _only_ be used for AppDirs that come with their own privately bundled interpreter and libc ("bundle everything")?
* Is this tied to glibc specifically or can it also work with musl inside the AppDir?
* Where/how does the interpreter and libc need to be placed inside the AppDir?
* How does this AppRun determine which payload executable to launch? Does it read desktop files?
* How can one specify additional environment variables? E.g., things like https://github.com/probonopd/go-appimage/blob/1c66f8690baafa41e5255af8f9ea84c95e1fdbcf/src/appimagetool/appdirtool.go#L47-L128

It would also be helpful to clarify similarities/differences to similar projects. Do you think this is/can be a suitable replacement for 
* https://github.com/probonopd/libhookexecv (in other words: Can it be used for WINE?)
* https://invent.kde.org/brauch/appimage-exec-wrapper

Do you think one could (optionally) combine it with functionality like https://github.com/project-portable/libunionpreload provides? This would allow for applications that have absolute paths compiled in to run.

**Comment by probonopd** [comment]
> Where/how does the interpreter and libc need to be placed inside the AppDir?

Looks like it can be specified in the `.env` file. Is this documented somewhere, especially which variables mean what?

**Comment by azubieta** [comment]
>> Can this only be used for AppDirs that come with their own privately bundled interpreter and libc ("bundle everything")?

- AppRun does expect that there is a bundled interpreter and libc.

- libapprun_hooks don't does expect that there is a bundled interpreter and libc, it only hooks execv calls

>> Is this tied to glibc specifically or can it also work with musl inside the AppDir?

- I need to investigate a bit more about musl. In theory it should work if rebuilt for musl, but maybe we need to make some adjustments to the excev hooks

>> Where/how does the interpreter and libc need to be placed inside the AppDir?

- In a place where the libs that are strongly bundled to then doesn't interfere with the rest of the package. appimage-builder uses `AppDir/opt/glibc` as prefix when deploying the libc package.  

>> How does this AppRun determine which payload executable to launch? Does it read desktop files?

- It's specified using a environment variable from the `.env` file. I put everything in a single file to avoid reading several files.  The payload executable is specified at `EXEC_PATH`, arguments are specified at `EXEC_ARGS`

>> How can one specify additional environment variables?

- Add them to the `.env` file like this:

```
APPRUN_ORIGINAL_PYTHONHOME="" # value before the AppImage is started
PYTHONHOME=$APPDIR/usr # value while the AppImage is running
APPRUN_STARTUP_PYTHONHOME="" # value set for starting the AppImage, it's used to detect whether the value changed during the execution.
```

**Comment by azubieta** [comment]
>> It would also be helpful to clarify similarities/differences to similar projects. Do you think this is/can be a suitable replacement for

    https://github.com/probonopd/libhookexecv (in other words: Can it be used for WINE?)
    https://invent.kde.org/brauch/appimage-exec-wrapper

Actually I took those projects as inspiration, so yes it should be possible to replace then. But I haven't tried to do it.

**Comment by azubieta** [comment]
>> Do you think one could (optionally) combine it with functionality like https://github.com/project-portable/libunionpreload provides? This would allow for applications that have absolute paths compiled in to run.

That would be a huge addition, I'll get to it ASAP #8

**Comment by azubieta** [comment]
I just updated the project README with the AppRun documentation. Please take another look to it.

**Comment by probonopd** [comment]
Thank you very much @azubieta. Documentation makes this project _so_ much more useful ;-)

I will have a try at using this `AppRun` and might reopen in case some things are still unclear. Until then, closing.
