### ISSUE TITLE
Getting segfault when trying to use libapprun_hooks

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/AppRun#7]
In an effort to solve https://github.com/probonopd/go-appimage/issues/49, I was trying to use `libapprun_hooks.so` with an existing AppImage.

To reproduce:

1. Download https://timepirate.org/downloads/Commandoo.tar.gz and get the AppImage contained therein
2. Run the AppImage (it works)
3. Unpack the AppImage
4. Replace AppRun with the script below, make it executable
5. Download libapprun_hooks.so and put it in usr/lib64
6. Try to run

```
#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"

MAIN=$(grep -r "^Exec=.*" "$HERE"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
MAIN_BIN=$(find "$HERE/usr/bin" -name "$MAIN" | head -n 1)
LD_LINUX=$(find "$HERE" -name 'ld-*.so.*' | head -n 1)

echo "Run $MAIN_BIN from experimental self-contained bundle"

export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
export INTERPRETER="${LD_LINUX}"
export LD_PRELOAD=libapprun_hooks.so

exec "${MAIN_BIN}" "$@"
```

Result:

```
me@host:~/squashfs-root$ ./AppRun 
Run /home/me/squashfs-root/usr/bin/commandoo from experimental self-contained bundle
Segmentation fault
```

What am I doing wrong?

**Comment by azubieta** [comment]
I got a 404 when trying to download the file you reference above.

Regarding your code, `libapprun_hooks.so` function is to remove AppImage specific variables when the process is forked by using of `execv` or some derivative.

You still need AppRun to resolve the right ld-linux, notice that you must specify the path to the system ld-linux, and the path to the bundle ld-linux. You can inspect an AppImage packaged with appimage-builder for details.


https://github.com/AppImageCrafters/appimage-manager/releases/download/v0.1.2/app-0.1.0-x86_64.AppImage

**Comment by probonopd** [comment]
>You still need AppRun to resolve the right ld-linux, 

How is it doing that? I was suspecting that it was done by `LD_PRELOAD libapprun_hooks.so` but apparently there is more to it?

**Comment by probonopd** [comment]
>  You can inspect an AppImage packaged with appimage-builder for details.

Tried doing so but noticed variables that I don't quite understand the meaning of yet, hence #6... ;-)

**Comment by azubieta** [comment]
I left some answers on #6, I'll also improve the README

**Comment by azubieta** [comment]
Closing it, please reopen if the problem persist.

**Comment by probonopd** [comment]
As per https://github.com/AppImageCrafters/AppRun/issues/11#issuecomment-679281570, the bash `AppRun` that I have so far is not sufficient. So let's focus on the `.env` for the binary `AppRun` for now. Any ideas @azubieta?

**Comment by azubieta** [comment]
> So it seems like the bundled libc is not used even

`AppRun` guess wich glib to use by reading the libc.so file. 

`strings /lib/x86_64-linux-gnu/libc-2.27.so | grep GLIBC_`

If the system glib version is greater than the bundled one the you set `LD_LIBRARY_PATH` to `$APPDIR_LIBRARY_PATH:$LD_LIBRARY_PATH`. 

if the bundled glib version is greater then set `LD_LIBRARY_PATH` to `$LIBC_LIBRARY_PATH:$APPDIR_LIBRARY_PATH:$LD_LIBRARY_PATH`. 

I guess that I should add this to the documentation too.

Notice that you will have to bundle grep, cut and other command you use in your bash script. There will be race conditions with those commands and they dependencies. That's why I created a statically linked binary for the AppRun.

**Comment by probonopd** [comment]
I see. Do you understand why this AppDir fails with the statically linked binary for the AppRun?

**Comment by Juuliuus** [comment]
Hi @azubieta and @probonopd , please see my solution to this problem at:

[https://github.com/probonopd/go-appimage/issues/49](url)

**Comment by probonopd** [comment]
Wdyt @azubieta? I still think we should find a solution that removes the need to copy ld-linux to /tmp...

**Comment by azubieta** [comment]
Prefix ld-linux on each execve call has a nasty side effect, it makes `/proc/self/exec` point to ld-linux instad of the executed binary. If we could make `/proc/self/exec` report the right path a lot of issues will be solved.
