### ISSUE TITLE
Allow for applications that have absolute paths compiled in to run.

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/AppRun#8]
Investigate https://github.com/project-portable/libunionpreload in order to port it's features into libapprun_hooks

**Comment by probonopd** [comment]
Since this adds some overhead (I think) it should be made an optional feature.

**Comment by azubieta** [comment]
Some overhead will be added, but I expect it to be quite insignificant. It will be an extra function call on file opening operations. There is no overhead on RW operations being those the more expensive. Me first call would be to keep the whole code together and perform tests. Then we can take a decision based on solid data.

**Comment by azubieta** [comment]
To allow an application with fixed paths we must intercept all the system calls that take a file path as argument and rewrite. `libunionfs` does this job quite well so we are going to copy this feature.

Two kind of overlay will be required:
- full overlay (no fallback to the root fs): this is required to avoid a given application to load non-compatible binaries from the system
- soft overlay, allows fallback to the system files. This is used in scenarios where the system files can be safely opened by the app, by example with icons.

**Comment by azubieta** [comment]
Changes merge to master preparing 1.2 release

New feature: Path mappings support
`APPRUN_PATH_MAPPINGS: /home/runner/work/Glimpse/Glimpse/glimpse-prefix/:usr/;`

**Comment by probonopd** [comment]
Very useful @azubieta. Will it be documented at https://github.com/AppImageCrafters/AppRun/blob/master/README.md?
